name: disc_golf_app
description: A disc golf throw analysis app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.8.2
  path_provider: ^2.1.2
  provider: ^6.1.1
  image_picker: ^1.1.0
  file_picker: ^8.1.2
  video_thumbnail: ^0.5.3
  google_mlkit_pose_detection: ^0.14.1
  shared_preferences: ^2.2.2
  tflite_flutter: ^0.12.1
  image: ^4.1.4
  ffmpeg_kit_flutter_new: ^4.1.0
  gal: ^2.3.0
  flutter_svg: ^2.0.10
  http: ^1.2.1
  archive: ^3.6.1
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/output_coordinates.json
    - assets/data/analysis_results.json
    - assets/data/pro_baseline_db.json
    - assets/models/disc_detector.tflite
    - assets/images/disc_golf_basket.svg
    - assets/data/knowledge_base.json
